### ISSUE TITLE
Lab 3: Run App Locally not building

### ISSUE THREAD

**Issue by hitchiceburg** [adrag239/northwind-traders#1]
Hi

I'm having a great time going through the **.NET Application Modernization**, but had to do some **hacks** to get it to work. 
In Lab 2, "Create VPC", I had to comment out the "using Constructs;" but still needed to roll back the Nuget package Constructs to < 4.0.  I did get things to compile and deploy. 

Then on to Lab 3.  Build App

npm install
`npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\zzzzz\northwind-traders\Src/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\zzzzz\northwind-traders\Src\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent`

then I run 
npm init 

then npm install
which worked, then 
npm run-script build
>npm ERR! Missing script: "build"

I haven't done any Angular before and very limited node.js. I'm sure there is something that I am missing here but I don't see it. 
I have 

Angular CLI: 13.1.1
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.1 (cli-only)
@angular-devkit/core         13.1.1 (cli-only)
@angular-devkit/schematics   13.1.1 (cli-only)
@schematics/angular          13.1.1 (cli-only)

Any ideas?
Thanks in advance.

**Comment by adrag239** [comment]
I think the issue is that you should run all npm commands from inside the "Src\WebUI\ClientApp" folder, that contains package.json file with all required references to npm packages with correct versions.

**Comment by hitchiceburg** [comment]
Yes, thats it. Thank you. I can't believe my brain didn't parse SrcWebUIClientApp. Thought that was one directory name. 
Thanks again.

**Comment by adrag239** [comment]
Oh, I see the problem in the lab guide now, for some reason all backslashes are gone from the code snippets. I'll check what has happened!

**Comment by hitchiceburg** [comment]
backslashes are present in the code snippets
